### ISSUE TITLE
The maxSupportVersion specified in the code is inconsistent with the one specified in the official doc

### ISSUE THREAD

**Issue by caidongqing** [vmware/load-balancer-and-ingress-services-for-kubernetes#1210] opened 2023-07-19 09:06 UTC
### Describe the bug

AKO 1.8.2 logs mention is supports up till AVI Controller version 22.1.2. However, AKO compatibility guide suggests it is compatible till 22.1.4 
Verified AKO 1.8.2 working fine with our AVI 22.1.3 version also. therefore reported message in log is incorrect.

Please find attached ako pod log file and support bundle

As per AVI Ref Link - https://avinetworks.com/docs/ako/1.8/ako-compatibility-guide/ 

AKO Release(s)		Avi Controller Versions Supported
==============		==================================
1.8					21.1.3 - 22.1.4 (AKO 1.8.2)

ako pod logs details (kubectl logs ako-0 -n avi-system):

2023-07-15T18:11:09.859Z        INFO    ako-main/main.go:71     AKO is running with version: v1.8.2
:
2023-07-15T18:11:10.504Z        INFO    lib/lib.go:1730 Setting the client version to AVI Max supported version 22.1.2
2023-07-15T18:11:10.504Z        INFO    cache/avi_ctrl_clients.go:71    Setting the client version to 22.1.2

Following issue observed: 

2023-07-15T18:11:09.859Z        INFO    api/api.go:52   Setting route for GET /api/status
2023-07-15T18:11:09.859Z        INFO    ako-main/main.go:71     AKO is running with version: v1.8.2
2023-07-15T18:11:09.859Z        INFO    ako-main/main.go:81     We are running inside kubernetes cluster. Won't use kubeconfig
 files.
2023-07-15T18:11:09.859Z        WARN    lib/lib.go:710  Unable to fetch Blocked namespaces from environment variables. unexpec
ted end of JSON input
2023-07-15T18:11:09.860Z        INFO    api/api.go:110  Starting API server at :8080
2023-07-15T18:11:09.870Z        INFO    lib/control_config.go:198       ako.vmware.com/v1alpha1/AviInfraSetting enabled on clu
ster
2023-07-15T18:11:09.903Z        INFO    lib/control_config.go:207       ako.vmware.com/v1alpha1/HostRule enabled on cluster
2023-07-15T18:11:09.934Z        INFO    lib/control_config.go:216       ako.vmware.com/v1alpha1/HTTPRule enabled on cluster
2023-07-15T18:11:09.946Z        INFO    ako-main/main.go:150    Kubernetes cluster apiserver version 1.24
2023-07-15T18:11:09.953Z        INFO    utils/utils.go:168      Initializing configmap informer in avi-system
2023-07-15T18:11:09.953Z        INFO    lib/dynamic_client.go:118       Skipped initializing dynamic informers antrea
2023-07-15T18:11:10.102Z        INFO    k8s/ako_init.go:455     Successfully connected to AVI controller using existing AKO se
cret
2023-07-15T18:11:10.102Z        INFO    ako-main/main.go:261    Valid Avi Secret found, continuing ..
2023-07-15T18:11:10.504Z        INFO    lib/lib.go:1730 Setting the client version to AVI Max supported version 22.1.2
2023-07-15T18:11:10.504Z        INFO    cache/avi_ctrl_clients.go:71    Setting the client version to 22.1.2
2023-07-15T18:11:10.504Z        INFO    ako-main/main.go:279    SEgroup name found, continuing ..
2023-07-15T18:11:11.650Z        INFO    cache/controller_obj_cache.go:2340      Avi cluster state is CLUSTER_UP_NO_HA
2023-07-15T18:11:11.785Z        INFO    cache/controller_obj_cache.go:2901      Setting cloud vType: CLOUD_VCENTER
2023-07-15T18:11:11.785Z        INFO    cache/controller_obj_cache.go:2904      Setting cloud uuid: cloud-ba12c31e-dc83-4a73-9

### Reproduction steps

1. Check ako-o pod logs using kubectl logs command
    kubectl logs ako-0 -n avi-system
2. Observer message :  Setting the client version to AVI Max supported version 22.1.2  ( But actually ako 1.8.2 supported version is 22.1.4) 

### Expected behavior

If the CTRL_VERSION (controllerVersion) is set a large version than the AviMaxSupportedVersion such as 22.1.4, it will get the  22.1.2 version
```
if CompareVersions(controllerVersion, ">", GetAviMaxSupportedVersion()) {
		utils.AviLog.Infof("Setting the client version to AVI Max supported version %s", GetAviMaxSupportedVersion())
		controllerVersion = GetAviMaxSupportedVersion()
	}
```

**Comment by akshayhavile** [comment] 2023-07-26 10:48
@caidongqing: AKO 1.8.2 does support Avi controller version 22.1.3 and above with API Version set as 22.1.2 Log messages are correct.  So this is not a bug. I will close this.

**Closed by akshayhavile** 2023-07-26 10:48 UTC
Labels: bug
